lib/taskTracker_web/router.ex
defmodule TaskTrackerWeb.Router do
  use TaskTrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TaskTrackerWeb.Plugs.FetchSession
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :ajax do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_flash
    plug TaskTrackerWeb.Plugs.FetchSession # FIXME: "FetchUser"
  end

  scope "/ajax", TaskTrackerWeb do
    pipe_through :ajax
    resources "/timeblocks", TimeBlockController, except: [:new, :edit]
  end

  scope "/", TaskTrackerWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/tasks", TaskController
    resources "/users", UserController
    resources "/sessions", SessionController, only: [:create, :delete], singleton: true
  end

  # Other scopes may use custom stacks.
  # scope "/api", TaskTrackerWeb do
  #   pipe_through :api
  # end
end

lib/taskTracker_web/views/layout_view.ex
defmodule TaskTrackerWeb.LayoutView do
  use TaskTrackerWeb, :view
end

lib/taskTracker_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>TaskTracker</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>

  
  <body>
  
    <div class="container">
    
      <nav class="navbar navbar-expand-sm navbar-light bg-white">
      <a class="navbar-brand" href="/tasks"><h1>Task Tracker!</h1></a>
      
      <%= if @current_user do %>
        <div class="col-8">
          <ul class="navbar-nav mr-auto">
                <p class="my-3">
                  User: <%= @current_user.email %> |
                  <%= link("Logout", class: "btn btn-info btn-xs", to: Routes.session_path(@conn, :delete), method: :delete) %>
                  <%= link("My Profile", class: "btn btn-info btn-xs", to: Routes.user_path(@conn, :show, @current_user))%>
                  <%= link("Tasks", class: "btn btn-info btn-xs", to: Routes.task_path(@conn, :index))%> 
                </p>
          </ul>
        </div>
      <% end %>

      </nav>

      <div class="row">
        <div class="col-12">
          <%= if get_flash(@conn, :info) do %>
            <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
          <% end %>
          <%= if get_flash(@conn, :error) do %>
            <p class="alert alert-danger" role="alert">
              <%= get_flash(@conn, :error) %>
            </p>
          <% end %>
        </div>
      </div>

      <%= render @view_module, @view_template, assigns %>
    </div>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>